insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Bosnia and Herzegovina', 'BA');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('Tokelau', 'TK');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Saudi Arabia', 'SA');
insert into paises (nombre, nombre_alfa2) values ('Fiji', 'FJ');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Democratic Republic of the Congo', 'CD');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('Thailand', 'TH');
insert into paises (nombre, nombre_alfa2) values ('Chile', 'CL');
insert into paises (nombre, nombre_alfa2) values ('Brazil', 'BR');
insert into paises (nombre, nombre_alfa2) values ('Russia', 'RU');
insert into paises (nombre, nombre_alfa2) values ('France', 'FR');
insert into paises (nombre, nombre_alfa2) values ('Thailand', 'TH');
insert into paises (nombre, nombre_alfa2) values ('Senegal', 'SN');
insert into paises (nombre, nombre_alfa2) values ('Costa Rica', 'CR');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('Belarus', 'BY');
insert into paises (nombre, nombre_alfa2) values ('Portugal', 'PT');
insert into paises (nombre, nombre_alfa2) values ('Hong Kong', 'HK');
insert into paises (nombre, nombre_alfa2) values ('Kyrgyzstan', 'KG');
insert into paises (nombre, nombre_alfa2) values ('Philippines', 'PH');
insert into paises (nombre, nombre_alfa2) values ('France', 'FR');
insert into paises (nombre, nombre_alfa2) values ('Nigeria', 'NG');
insert into paises (nombre, nombre_alfa2) values ('Israel', 'IL');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('North Korea', 'KP');
insert into paises (nombre, nombre_alfa2) values ('Greece', 'GR');
insert into paises (nombre, nombre_alfa2) values ('United States', 'US');
insert into paises (nombre, nombre_alfa2) values ('Japan', 'JP');
insert into paises (nombre, nombre_alfa2) values ('Portugal', 'PT');
insert into paises (nombre, nombre_alfa2) values ('Dominican Republic', 'DO');
insert into paises (nombre, nombre_alfa2) values ('Pakistan', 'PK');
insert into paises (nombre, nombre_alfa2) values ('Brazil', 'BR');
insert into paises (nombre, nombre_alfa2) values ('Portugal', 'PT');
insert into paises (nombre, nombre_alfa2) values ('Sweden', 'SE');
insert into paises (nombre, nombre_alfa2) values ('Honduras', 'HN');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('Nigeria', 'NG');
insert into paises (nombre, nombre_alfa2) values ('Brazil', 'BR');
insert into paises (nombre, nombre_alfa2) values ('Bulgaria', 'BG');
insert into paises (nombre, nombre_alfa2) values ('Mexico', 'MX');
insert into paises (nombre, nombre_alfa2) values ('Sweden', 'SE');
insert into paises (nombre, nombre_alfa2) values ('Portugal', 'PT');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('France', 'FR');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Argentina', 'AR');
insert into paises (nombre, nombre_alfa2) values ('Paraguay', 'PY');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Sweden', 'SE');
insert into paises (nombre, nombre_alfa2) values ('Argentina', 'AR');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Philippines', 'PH');
insert into paises (nombre, nombre_alfa2) values ('Brazil', 'BR');
insert into paises (nombre, nombre_alfa2) values ('France', 'FR');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Colombia', 'CO');
insert into paises (nombre, nombre_alfa2) values ('Pakistan', 'PK');
insert into paises (nombre, nombre_alfa2) values ('Russia', 'RU');
insert into paises (nombre, nombre_alfa2) values ('Luxembourg', 'LU');
insert into paises (nombre, nombre_alfa2) values ('Albania', 'AL');
insert into paises (nombre, nombre_alfa2) values ('Pakistan', 'PK');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Brazil', 'BR');
insert into paises (nombre, nombre_alfa2) values ('Philippines', 'PH');
insert into paises (nombre, nombre_alfa2) values ('Palestinian Territory', 'PS');
insert into paises (nombre, nombre_alfa2) values ('France', 'FR');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('Russia', 'RU');
insert into paises (nombre, nombre_alfa2) values ('Russia', 'RU');
insert into paises (nombre, nombre_alfa2) values ('Sweden', 'SE');
insert into paises (nombre, nombre_alfa2) values ('Mongolia', 'MN');
insert into paises (nombre, nombre_alfa2) values ('Peru', 'PE');
insert into paises (nombre, nombre_alfa2) values ('Sweden', 'SE');
insert into paises (nombre, nombre_alfa2) values ('Peru', 'PE');
insert into paises (nombre, nombre_alfa2) values ('Poland', 'PL');
insert into paises (nombre, nombre_alfa2) values ('Philippines', 'PH');
insert into paises (nombre, nombre_alfa2) values ('Russia', 'RU');
insert into paises (nombre, nombre_alfa2) values ('France', 'FR');
insert into paises (nombre, nombre_alfa2) values ('China', 'CN');
insert into paises (nombre, nombre_alfa2) values ('Indonesia', 'ID');
insert into paises (nombre, nombre_alfa2) values ('Jordan', 'JO');
insert into paises (nombre, nombre_alfa2) values ('Palestinian Territory', 'PS');
insert into paises (nombre, nombre_alfa2) values ('Philippines', 'PH');
insert into paises (nombre, nombre_alfa2) values ('Sweden', 'SE');
insert into paises (nombre, nombre_alfa2) values ('Vietnam', 'VN');
insert into paises (nombre, nombre_alfa2) values ('Bulgaria', 'BG');
